# Generated by Django 2.2.16 on 2021-11-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='ZDuuk85DM2', max_length=20),
        ),
    ]
