# Generated by Django 2.2.16 on 2021-11-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211113_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='vrhjiASUAm', max_length=20),
        ),
    ]
